# ---
# Basic Configuration
# ---
mixed-port: 7890
redir-port: 7892
allow-lan: false
ipv6: false
mode: Rule
log-level: info
external-controller: "127.0.0.1:9090"
secret: ""
profile:
  store-selected: true
  store-fake-ip: false

sniffer:
  enable: true
  override-destination: true
  parse-pure-ip: false
  force-dns-mapping: false
  sniff:
    TLS:
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
  force-domain:
    - "+.netflix.com"
    - "+.nflxvideo.net"
    - "+.amazonaws.com"
    - "+.media.dssott.com"
  skip-domain:
    - "+.apple.com"
    - "+.push.apple.com"
    - "+.icloud.com"
    - "+.icloud-content.com"
    - "+.mzstatic.com"
    - "+.itunes.apple.com"
    - "+.todesk.com"
    - "+.oray.com"

tun:
  enable: true
  dns-hijack: [0.0.0.0:53]
  auto-detect-interface: true 
  auto-route: true
  auto-redirect: true
  strict-route: false
  endpoint-independent-nat: true

dns:
  enable: true
  ipv6: false
  use-system-hosts: false
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*.lan"
    - "localhost"
    - "*.local"
    - "stun.*.*.*"
    - "stun.*.*"
    - "time.windows.com"
    - "time.nist.gov"
    - "time.apple.com"
    - "time.asia.apple.com"
    - "*.ntp.org.cn"
    - "*.openwrt.pool.ntp.org"
    - "time1.cloud.tencent.com"
    - "time.ustc.edu.cn"
    - "pool.ntp.org"
    - "ntp.ubuntu.com"
    - "ntp.aliyun.com"
    - "ntp1.aliyun.com"
    - "ntp2.aliyun.com"
    - "ntp3.aliyun.com"
    - "ntp4.aliyun.com"
    - "ntp5.aliyun.com"
    - "ntp6.aliyun.com"
    - "ntp7.aliyun.com"
    - "time1.aliyun.com"
    - "time2.aliyun.com"
    - "time3.aliyun.com"
    - "time4.aliyun.com"
    - "time5.aliyun.com"
    - "time6.aliyun.com"
    - "time7.aliyun.com"
    - "*.time.edu.cn"
    - "time1.apple.com"
    - "time2.apple.com"
    - "time3.apple.com"
    - "time4.apple.com"
    - "time5.apple.com"
    - "time6.apple.com"
    - "time7.apple.com"
    - "time1.google.com"
    - "time2.google.com"
    - "time3.google.com"
    - "time4.google.com"
    - "music.163.com"
    - "*.music.163.com"
    - "*.126.net"
    - "musicapi.taihe.com"
    - "music.taihe.com"
    - "songsearch.kugou.com"
    - "trackercdn.kugou.com"
    - "*.kuwo.cn"
    - "api-jooxtt.sanook.com"
    - "api.joox.com"
    - "joox.com"
    - "y.qq.com"
    - "*.y.qq.com"
    - "streamoc.music.tc.qq.com"
    - "mobileoc.music.tc.qq.com"
    - "isure.stream.qqmusic.qq.com"
    - "dl.stream.qqmusic.qq.com"
    - "aqqmusic.tc.qq.com"
    - "amobile.music.tc.qq.com"
    - "*.xiami.com"
    - "*.music.migu.cn"
    - "music.migu.cn"
    - "*.msftconnecttest.com"
    - "*.msftncsi.com"
    - "localhost.ptlogin2.qq.com"
    - "*.*.*.srv.nintendo.net"
    - "*.*.stun.playstation.net"
    - "xbox.*.*.microsoft.com"
    - "*.ipv6.microsoft.com"
    - "*.*.xboxlive.com"
    - "speedtest.cros.wr.pvp.net"
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  proxy-server-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  skip-cert-verify: false
  follow-rule: false

proxy-providers:
  Tag:
    type: http
    url: <subscription_url>
    path: ./proxy_provider/tag.yaml
    interval: 3600
    health-check:
      enable: true
      url: http://www.apple.com/library/test/success.html
      interval: 600
    benchmark-url: http://www.apple.com/library/test/success.html
    benchmark-timeout: 3

proxy-groups:
  - name: 🎯 AI
    type: select
    icon: https://raw.githubusercontent.com/lychileng/Ladder/refs/heads/main/ICON/Service/openai.png
    proxies:
      - 🛰️ Taiwan
      - 🛰️ Singapore
      - 🛰️ Japan
      - 🛰️ AI Prime
  - name: 🎯 Social
    type: select
    icon: https://raw.githubusercontent.com/lychileng/Ladder/refs/heads/main/ICON/Service/x.png
    proxies:
      - 🛰️ Taiwan
      - 🛰️ Hong Kong
      - 🛰️ Singapore
      - 🛰️ Japan
      - 🛰️ South Korea
      - 🛰️ United States
      - 🛰️ Worldwide
  - name: 🎯 Stream
    type: select
    icon: https://raw.githubusercontent.com/lychileng/Ladder/refs/heads/main/ICON/Service/youtube.png
    proxies:
      - 🛰️ Taiwan
      - 🛰️ Hong Kong
      - 🛰️ Singapore
      - 🛰️ Japan
      - 🛰️ South Korea
      - 🛰️ United States
      - 🛰️ Worldwide
  - name: 🎯 Crypto
    type: select
    icon: https://raw.githubusercontent.com/lychileng/Ladder/refs/heads/main/ICON/Service/bitcoin.png
    proxies:
      - 🛰️ Singapore
      - 🛰️ Hong Kong
      - 🛰️ Taiwan
      - 🛰️ Japan
      - DIRECT
  - name: 🎯 Offshore
    type: select
    icon: https://raw.githubusercontent.com/lychileng/Ladder/refs/heads/main/ICON/Service/hsbc.png
    proxies:
      - DIRECT
      - 🛰️ Taiwan
      - 🛰️ Hong Kong
      - 🛰️ Singapore
  - name: 🎯 Apple
    type: select
    icon: https://raw.githubusercontent.com/lychileng/Ladder/refs/heads/main/ICON/Service/apple.png
    proxies:
      - DIRECT
      - 🛰️ Taiwan
      - 🛰️ Hong Kong
      - 🛰️ Singapore
      - 🛰️ Japan
      - 🛰️ South Korea
      - 🛰️ United States
  - name: 🎯 Final
    type: select
    icon: https://raw.githubusercontent.com/lychileng/Ladder/refs/heads/main/ICON/Service/global.png
    proxies:
      - 🛰️ Taiwan
      - 🛰️ Hong Kong
      - 🛰️ Singapore
      - 🛰️ Japan
      - 🛰️ South Korea
      - 🛰️ United States
      - 🛰️ Worldwide
      - DIRECT
  - name: 🛰️ Taiwan
    type: url-test
    include-all: true
    filter: "台|🇼🇸|🇹🇼|TW|(?i)Taiwan"
    interval: 600
    lazy: false
    tolerance: 80
    url: http://www.apple.com/library/test/success.html
    benchmark-timeout: 3
    icon: https://raw.githubusercontent.com/lychileng/Ladder/refs/heads/main/ICON/Flag/TW.png
  - name: 🛰️ Hong Kong
    type: url-test
    include-all: true
    filter: "港|🇭🇰|HK|(?i)Hong"
    interval: 600
    lazy: false
    tolerance: 80
    url: http://www.apple.com/library/test/success.html
    benchmark-timeout: 3
    icon: https://raw.githubusercontent.com/lychileng/Ladder/refs/heads/main/ICON/Flag/HK.png
  - name: 🛰️ Singapore
    type: url-test
    include-all: true
    filter: "新加坡|坡|🇸🇬|SG|(?i)Singapore"
    interval: 600
    lazy: false
    tolerance: 80
    url: http://www.apple.com/library/test/success.html
    benchmark-timeout: 3
    icon: https://raw.githubusercontent.com/lychileng/Ladder/refs/heads/main/ICON/Flag/SG.png
  - name: 🛰️ Japan
    type: url-test
    include-all: true
    filter: "日|🇯🇵|JP|(?i)Japan"
    interval: 600
    lazy: false
    tolerance: 80
    url: http://www.apple.com/library/test/success.html
    benchmark-timeout: 3
    icon: https://raw.githubusercontent.com/lychileng/Ladder/refs/heads/main/ICON/Flag/JP.png
  - name: 🛰️ South Korea
    type: url-test
    include-all: true
    filter: "韩|🇰🇷|KR|(?i)Korea"
    interval: 1800
    lazy: true
    tolerance: 100
    url: http://www.apple.com/library/test/success.html
    benchmark-timeout: 3
    icon: https://raw.githubusercontent.com/lychileng/Ladder/refs/heads/main/ICON/Flag/KR.png
  - name: 🛰️ United States
    type: url-test
    include-all: true
    filter: "美|🇺🇸|US|(?i)States|America"
    interval: 1800
    lazy: true
    tolerance: 100
    url: http://www.apple.com/library/test/success.html
    benchmark-timeout: 3
    icon: https://raw.githubusercontent.com/lychileng/Ladder/refs/heads/main/ICON/Flag/US.png
  - name: 🛰️ Worldwide
    type: url-test
    include-all: true
    filter: "^(?!.*(AI-Prime|美|US|USA|Japan|日|JP|Taiwan|台|TW|Singapore|新|SG|Korea|韩|韓|KR|(?i)Hong|港|HK)).*"
    interval: 1800
    lazy: true
    tolerance: 100
    url: http://www.apple.com/library/test/success.html
    benchmark-timeout: 3
    icon: https://raw.githubusercontent.com/lychileng/Ladder/refs/heads/main/ICON/Flag/WW.png
  - name: 🛰️ AI Prime
    type: url-test
    include-all: true
    filter: ".*AI.*"
    interval: 1800
    lazy: true
    tolerance: 100
    url: http://www.apple.com/library/test/success.html
    benchmark-timeout: 3
    icon: https://raw.githubusercontent.com/lychileng/Ladder/refs/heads/main/ICON/Flag/AI.png

rule-providers:
  Mainland:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/lychileng/Ladder/refs/heads/main/Stash/Rules/Mainland.yaml
    path: ./rules/mainland.yaml
    interval: 86400
  AI:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/lychileng/Ladder/refs/heads/main/Stash/Rules/AI.yaml
    path: ./rules/ai.yaml
    interval: 86400
  Develop:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/lychileng/Ladder/refs/heads/main/Stash/Rules/Develop.yaml
    path: ./rules/develop.yaml
    interval: 86400
  Offshore:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/lychileng/Ladder/refs/heads/main/Stash/Rules/Offshore.yaml
    path: ./rules/offshore.yaml
    interval: 86400
  Crypto:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/lychileng/Ladder/refs/heads/main/Stash/Rules/Crypto.yaml
    path: ./rules/crypto.yaml
    interval: 86400
  Apple:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/lychileng/Ladder/refs/heads/main/Stash/Rules/Apple.yaml
    path: ./rules/apple.yaml
    interval: 86400
  Microsoft:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/lychileng/Ladder/refs/heads/main/Stash/Rules/Microsoft.yaml
    path: ./rules/microsoft.yaml
    interval: 86400
  GlobalMedia:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/lychileng/Ladder/refs/heads/main/Stash/Rules/GlobalMedia.yaml
    path: ./rules/globalmedia.yaml
    interval: 86400
  SNS:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/lychileng/Ladder/refs/heads/main/Stash/Rules/SNS.yaml
    path: ./rules/sns.yaml
    interval: 86400
  Nike:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/lychileng/Ladder/refs/heads/main/Stash/Rules/Nike.yaml
    path: ./rules/nike.yaml
    interval: 86400
  Advertising:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/lychileng/Ladder/refs/heads/main/Stash/Rules/AdvertisingLite.yaml
    path: ./rules/advertising.yaml
    interval: 86400

rules:
  # Remote
  - RULE-SET,AI,🎯 AI
  - RULE-SET,Offshore,🎯 Offshore
  - RULE-SET,Crypto,🎯 Crypto
  - RULE-SET,Apple,🎯 Apple
  - RULE-SET,Microsoft,🎯 Apple
  - RULE-SET,Develop,🎯 AI
  - RULE-SET,SNS,🎯 Social
  - RULE-SET,GlobalMedia,🎯 Stream
  - RULE-SET,Nike,🛰️ Hong Kong
  - RULE-SET,Advertising,REJECT
  - RULE-SET,Mainland,DIRECT
  # Local
  - DOMAIN-SUFFIX,cmynetwork.com,🎯 Final
  - DOMAIN,api.binance.com,DIRECT
  - DOMAIN-SUFFIX,binance.com,DIRECT
  - DOMAIN-SUFFIX,binance.org,DIRECT
  - DOMAIN-SUFFIX,fiat24.com,DIRECT
  - DOMAIN-SUFFIX,wiz.money,DIRECT
  - DOMAIN-SUFFIX,lichess.org,DIRECT
  - DOMAIN-SUFFIX,fotmob.com,🛰️ Hong Kong
  - DOMAIN-SUFFIX,ftchinese.com,DIRECT
  - DOMAIN-KEYWORD,adobe,REJECT
  # CIDR
  - IP-CIDR,100.64.0.0/10,DIRECT,no-resolve
  - IP-CIDR,169.254.0.0/16,DIRECT,no-resolve
  - IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
  - IP-CIDR,10.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,172.16.0.0/12,DIRECT,no-resolve
  - IP-CIDR,127.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,255.255.255.255/32,DIRECT,no-resolve
  - IP-CIDR,224.0.0.0/4,DIRECT,no-resolve
  - IP-CIDR6,::1/128,DIRECT,no-resolve
  - IP-CIDR6,fc00::/7,DIRECT,no-resolve
  - IP-CIDR6,fe80::/10,DIRECT,no-resolve
  - IP-CIDR6,ff00::/8,DIRECT,no-resolve
  # Geo
  - GEOIP,LAN,DIRECT,no-resolve
  - GEOIP,CN,DIRECT,no-resolve
  # Final
  - MATCH,🎯 Final
